version: "3.7"
services:
  database:
    image: mysql:8
    container_name: database
    # volumes: 
    #   - './mysql-docker:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dockerimage   
      MYSQL_USER: joeren
      MYSQL_PASSWORD: joeren
    ports:
      - 3308:3306
    networks:
      - backend
    restart: always
  spring-boot-app:
    build:
      context: ./sprbt-docker/
      dockerfile: dockerfile
    container_name: springboot-app
    depends_on:
      - database
    ports:
      - "9292:9292"
    networks:
      - backend
      - frontend
    restart: always
  angular-app:
    build:
      context: ./angul-docker/
      dockerfile: dockerfile
    container_name: angular-app
    ports:
      - "4300:80"
    networks:
      - frontend 
    restart: always         
networks:
  frontend:
  backend: